const SHORT_FILM_DURATION = 40;
const MOBILE_WIDTH = 480;
const MEDIUM_WIDTH = 750;
const LARGE_WIDTH = 1000;

const MOBILE_INITIAL_CARDS_COUNT = 5;
const MOBILE_MEDIUM_INITIAL_CARDS_COUNT = 8;
const MEDIUM_LARGE_INITIAL_CARDS_COUNT = 12;
const LARGE_INITIAL_CARDS_COUNT = 16;


const MOBILE_MORE_CARDS_COUNT = 1;
const MOBILE_MEDIUM_MORE_CARDS_COUNT = 2;
const MEDIUM_LARGE_MORE_CARDS_COUNT = 3;
const LARGE_MORE_CARDS_COUNT = 4;

export const constants = {
  SHORT_FILM_DURATION,
  MOBILE_WIDTH,
  MEDIUM_WIDTH,
  LARGE_WIDTH,
  MOBILE_INITIAL_CARDS_COUNT,
  MOBILE_MEDIUM_INITIAL_CARDS_COUNT,
  MEDIUM_LARGE_INITIAL_CARDS_COUNT,
  LARGE_INITIAL_CARDS_COUNT,
  MOBILE_MORE_CARDS_COUNT,
  MOBILE_MEDIUM_MORE_CARDS_COUNT,
  MEDIUM_LARGE_MORE_CARDS_COUNT,
  LARGE_MORE_CARDS_COUNT,
}
